# Generated by Django 5.2.17 on 2026-08-19 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Continente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Continente',
                'verbose_name_plural': 'Continentes',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Episodio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Episódio',
                'verbose_name_plural': 'Episódios',
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Gênero',
                'verbose_name_plural': 'Gêneros',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('continente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paises', to='app.continente')),
            ],
            options={
                'verbose_name': 'País',
                'verbose_name_plural': 'Países',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('site', models.URLField(blank=True, null=True)),
                ('insta', models.CharField(blank=True, max_length=150, null=True, verbose_name='Instagram')),
                ('face', models.CharField(blank=True, max_length=150, null=True, verbose_name='Facebook')),
                ('twitter', models.CharField(blank=True, max_length=150, null=True, verbose_name='Twitter')),
                ('nacionalidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pessoas', to='app.pais')),
            ],
            options={
                'verbose_name': 'Pessoa (Ator/Diretor)',
                'verbose_name_plural': 'Pessoas (Atores/Diretores)',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('duracao', models.DurationField(help_text='Formato: HH:MM:SS')),
                ('sinopse', models.TextField(blank=True, null=True)),
                ('site_oficial', models.URLField(blank=True, null=True)),
                ('data_lancamento', models.DateField()),
                ('nota_avaliacao', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('genero', models.ManyToManyField(blank=True, related_name='filmes', to='app.genero')),
                ('pais', models.ManyToManyField(blank=True, related_name='filmes', to='app.pais')),
                ('diretor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filmes_dirigidos', to='app.pessoa')),
            ],
            options={
                'verbose_name': 'Filme',
                'verbose_name_plural': 'Filmes',
                'ordering': ['-data_lancamento'],
            },
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('duracao', models.DurationField(help_text='Duração média por episódio - Formato: HH:MM:SS')),
                ('sinopse', models.TextField(blank=True, null=True)),
                ('site_oficial', models.URLField(blank=True, null=True)),
                ('data_lancamento', models.DateField()),
                ('nota_avaliacao', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('diretor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='series_dirigidas', to='app.pessoa')),
                ('genero', models.ManyToManyField(blank=True, related_name='series', to='app.genero')),
                ('pais', models.ManyToManyField(blank=True, related_name='series', to='app.pais')),
            ],
            options={
                'verbose_name': 'Série',
                'verbose_name_plural': 'Séries',
                'ordering': ['-data_lancamento'],
            },
        ),
        migrations.CreateModel(
            name='Temporada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(help_text='Ex: 1, 2, 3...')),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temporadas', to='app.serie')),
            ],
            options={
                'verbose_name': 'Temporada',
                'verbose_name_plural': 'Temporadas',
                'ordering': ['serie', 'numero'],
                'unique_together': {('serie', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='FilmeAtor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personagem', models.CharField(blank=True, max_length=150, null=True)),
                ('filme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elenco', to='app.filme')),
                ('ator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filmes_atuados', to='app.pessoa')),
            ],
            options={
                'verbose_name': 'Filme - Ator',
                'verbose_name_plural': 'Filmes - Atores',
                'unique_together': {('filme', 'ator')},
            },
        ),
        migrations.CreateModel(
            name='SerieEpisodio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duracao', models.DurationField(help_text='Formato: HH:MM:SS')),
                ('data_disponibilizacao', models.DateField()),
                ('episodio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series_episodios', to='app.episodio')),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodios_series', to='app.serie')),
                ('temporada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodios', to='app.temporada')),
            ],
            options={
                'verbose_name': 'Série - Episódio',
                'verbose_name_plural': 'Séries - Episódios',
                'ordering': ['serie', 'temporada', 'data_disponibilizacao'],
                'unique_together': {('temporada', 'episodio')},
            },
        ),
    ]
