# Generated by Django 5.2.17 on 2026-10-05 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('endereco', models.CharField(max_length=255)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(help_text='Sigla, ex: MG', max_length=2)),
                ('site', models.URLField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
            ],
            options={
                'verbose_name': 'Cinema',
                'verbose_name_plural': 'Cinemas',
                'ordering': ['cidade', 'nome'],
            },
        ),
        migrations.AddField(
            model_name='filme',
            name='backdrop_url',
            field=models.URLField(blank=True, help_text='URL da imagem de fundo (banner)', null=True),
        ),
        migrations.AddField(
            model_name='filme',
            name='data_estreia_cinema',
            field=models.DateField(blank=True, help_text='Data de estreia nos cinemas (pode ser diferente de data_lancamento)', null=True),
        ),
        migrations.AddField(
            model_name='filme',
            name='poster_url',
            field=models.URLField(blank=True, help_text='URL da capa/poster do filme', null=True),
        ),
        migrations.AddField(
            model_name='filme',
            name='status_cartaz',
            field=models.CharField(choices=[('em_cartaz', 'Em cartaz'), ('em_breve', 'Em breve'), ('fora_de_cartaz', 'Fora de cartaz')], default='fora_de_cartaz', help_text='Situação do filme nos cinemas', max_length=20),
        ),
        migrations.AddField(
            model_name='filme',
            name='tmdb_id',
            field=models.IntegerField(blank=True, help_text='ID do filme na API do TMDB', null=True, unique=True),
        ),
        migrations.CreateModel(
            name='Sessao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio_exibicao', models.DateField(help_text='Desde quando está passando neste cinema')),
                ('data_fim_exibicao', models.DateField(blank=True, help_text='Até quando fica em cartaz neste cinema (em branco = indefinido)', null=True)),
                ('formato', models.CharField(choices=[('2D', '2D'), ('3D', '3D'), ('IMAX', 'IMAX'), ('4DX', '4DX')], default='2D', max_length=10)),
                ('audio', models.CharField(choices=[('dublado', 'Dublado'), ('legendado', 'Legendado'), ('original', 'Idioma original')], default='dublado', max_length=10)),
                ('horarios', models.CharField(blank=True, help_text='Horários das sessões, separados por vírgula. Ex: 14:00, 17:30, 20:45', max_length=255, null=True)),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessoes', to='app.cinema')),
                ('filme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessoes', to='app.filme')),
            ],
            options={
                'verbose_name': 'Sessão',
                'verbose_name_plural': 'Sessões',
                'ordering': ['-data_inicio_exibicao'],
                'unique_together': {('filme', 'cinema', 'formato', 'audio')},
            },
        ),
    ]
