# Generated by Django 5.2.17 on 2026-10-05 23:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_cinema_filme_backdrop_url_filme_data_estreia_cinema_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AvaliacaoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.PositiveSmallIntegerField(help_text='Nota de 1 a 5 estrelas')),
                ('comentario', models.TextField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('filme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_usuarios', to='app.filme')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Avaliação de Usuário',
                'verbose_name_plural': 'Avaliações de Usuários',
                'ordering': ['-data_criacao'],
                'unique_together': {('filme', 'usuario')},
            },
        ),
    ]
