# Generated by Django 5.2.17 on 2026-10-06 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_avaliacaousuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='foto_url',
            field=models.URLField(blank=True, help_text='Foto do ator/diretor (TMDB)', null=True),
        ),
    ]
