# Generated by Django 5.2.17 on 2026-10-06 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_pessoa_foto_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Streaming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('tmdb_provider_id', models.IntegerField(blank=True, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Serviço de Streaming',
                'verbose_name_plural': 'Serviços de Streaming',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='FilmeStreaming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('assinatura', 'Incluído na assinatura'), ('aluguel', 'Aluguel'), ('compra', 'Compra')], default='assinatura', max_length=20)),
                ('filme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streamings', to='app.filme')),
                ('streaming', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filmes', to='app.streaming')),
            ],
            options={
                'verbose_name': 'Filme no Streaming',
                'verbose_name_plural': 'Filmes no Streaming',
                'unique_together': {('filme', 'streaming', 'tipo')},
            },
        ),
    ]
