# Generated by Django 5.2.17 on 2026-10-06 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_streaming_filmestreaming'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filme',
            name='status_cartaz',
            field=models.CharField(choices=[('em_cartaz', 'Em cartaz'), ('em_breve', 'Em breve'), ('lancado', 'Já lançado')], default='fora_de_cartaz', help_text='Situação do filme nos cinemas', max_length=20),
        ),
    ]
