# Generated by Django 5.2.17 on 2026-10-07 01:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_filme_status_cartaz'),
    ]

    operations = [
        migrations.AddField(
            model_name='filme',
            name='trailer_key',
            field=models.CharField(blank=True, help_text='ID do vídeo no YouTube (trailer)', max_length=30, null=True),
        ),
        migrations.CreateModel(
            name='FilmeImagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('ordem', models.PositiveSmallIntegerField(default=0)),
                ('filme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galeria', to='app.filme')),
            ],
            options={
                'verbose_name': 'Imagem do Filme',
                'verbose_name_plural': 'Galeria de Imagens',
                'ordering': ['ordem'],
            },
        ),
    ]
