# Generated by Django 5.2.17 on 2026-10-07 23:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_filme_trailer_key_filmeimagem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serieepisodio',
            name='episodio',
        ),
        migrations.RemoveField(
            model_name='serie',
            name='diretor',
        ),
        migrations.RemoveField(
            model_name='serie',
            name='genero',
        ),
        migrations.RemoveField(
            model_name='serie',
            name='pais',
        ),
        migrations.RemoveField(
            model_name='serieepisodio',
            name='serie',
        ),
        migrations.RemoveField(
            model_name='temporada',
            name='serie',
        ),
        migrations.RemoveField(
            model_name='serieepisodio',
            name='temporada',
        ),
        migrations.AlterField(
            model_name='filme',
            name='status_cartaz',
            field=models.CharField(choices=[('em_cartaz', 'Em cartaz'), ('em_breve', 'Em breve'), ('lancado', 'Já lançado')], default='lancado', help_text='Situação do filme no catálogo', max_length=20),
        ),
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_adicionado', models.DateTimeField(auto_now_add=True)),
                ('filme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritado_por', to='app.filme')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Favorito',
                'verbose_name_plural': 'Favoritos',
                'ordering': ['-data_adicionado'],
                'unique_together': {('filme', 'usuario')},
            },
        ),
        migrations.DeleteModel(
            name='Episodio',
        ),
        migrations.DeleteModel(
            name='Serie',
        ),
        migrations.DeleteModel(
            name='SerieEpisodio',
        ),
        migrations.DeleteModel(
            name='Temporada',
        ),
    ]
